name: "On Issue Opened"
on:
  issues:
    types: [opened, labeled, edited]

jobs:
  run:
    name: Run Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@lts
      - name: Run
        env:
          REPO_TOKEN: "${{ secrets.REPO_TOKEN }}"
        run: pnpm start
