name: "On Issue Opened"
on:
  issues:
    types: [opened, labeled]

jobs:
  run:
    name: Run Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
          runtime: node@lts
      - name: Run
        uses: ./
        with:
          github-token: "${{ secrets.REPO_TOKEN }}"
